config/routes.rb
# frozen_string_literal: true

Locations::Engine.routes.draw do
  resources :hours_locations, path_names: { new: 'create' }
  resources :holding_locations, path_names: { new: 'create' }
  resources :libraries, path_names: { new: 'create' }
  resources :delivery_locations, path_names: { new: 'create' }
  get 'digital_locations', to: 'delivery_locations#digital_locations'
  root 'home#index'
end

app/views/shared/_error_flash_message.html.erb
<h2><%= pluralize(flash[:error].count, "error") %> prohibited this from being saved:</h2>
<ul>
	<% flash[:error].each do |message| %>
		<li><%= message.html_safe %></li>
	<% end %>
</ul>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <%= type == 'error' ? (render partial: "shared/error_flash_message") : message.html_safe %>
  </div>
<% end %>

app/views/shared/_navbar.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'locations/home' %>"><%= link_to 'Locations Home', root_path %></li>
        <li class="<%= 'active' if params[:controller] == 'locations/delivery_locations' %>"><%= link_to 'Delivery Locations', delivery_locations_path %></li>
        <li class="<%= 'active' if params[:controller] == 'locations/holding_locations' %>"><%= link_to 'Holding Locations', holding_locations_path %></li>
        <li class="<%= 'active' if params[:controller] == 'locations/libraries' %>"><%= link_to 'Libraries', libraries_path %></li>
        <li class="<%= 'active' if params[:controller] == 'locations/hours_locations' %>"><%= link_to 'Hours Locations', hours_locations_path %></li>
      </ul>
  </div>
</nav>