config/routes.rb
# frozen_string_literal: true

Locations::Engine.routes.draw do
  resources :hours_locations, path_names: { new: 'create' }
  resources :holding_locations, path_names: { new: 'create' }
  resources :libraries, path_names: { new: 'create' }
  resources :delivery_locations, path_names: { new: 'create' }
  get 'digital_locations', to: 'delivery_locations#digital_locations'
  root 'home#index'
end

app/models/concerns/locations/coded.rb
# frozen_string_literal: true

module Locations
  module Coded
    extend ActiveSupport::Concern
    included do
      include FriendlyId
      friendly_id :code
      validates :code, presence: true
      validates :code, uniqueness: true
    end
  end
end

app/models/concerns/locations/labeled.rb
# frozen_string_literal: true

module Locations
  module Labeled
    extend ActiveSupport::Concern
    included do
      validates :label, presence: true
    end
  end
end

app/models/concerns/locations/with_library.rb
# frozen_string_literal: true

module Locations
  module WithLibrary
    extend ActiveSupport::Concern
    included do
      belongs_to :library, class_name: 'Locations::Library', foreign_key: :locations_library_id
      validates :library, presence: true
    end
  end
end

app/models/locations/delivery_location.rb
# frozen_string_literal: true

module Locations
  class DeliveryLocation < ActiveRecord::Base
    include Locations::Labeled
    include Locations::WithLibrary

    has_and_belongs_to_many :holding_locations, -> { distinct },
                            class_name: 'Locations::HoldingLocation',
                            join_table: 'locations_holdings_delivery',
                            foreign_key: 'locations_holding_location_id',
                            association_foreign_key: 'locations_delivery_location_id'

    validates :address, :phone_number, :contact_email, :gfa_pickup, presence: true
    validates :staff_only, :pickup_location, :digital_location, inclusion: { in: [true, false] }
    after_initialize :set_defaults

    private

    def set_defaults
      self.staff_only = false if staff_only.blank?
      self.pickup_location = false if pickup_location.blank?
      self.digital_location = false if digital_location.blank?
    end
  end
end

app/models/locations/floor.rb
module Locations
  class Floor < ActiveRecord::Base
    include Locations::Labeled
    include Locations::WithLibrary

    mount_uploader :floor_plan_image, FloorplanUploader

  end
end

app/models/locations/holding_location.rb
# frozen_string_literal: true

module Locations
  class HoldingLocation < ActiveRecord::Base
    include Locations::Coded
    include Locations::WithLibrary

    belongs_to :hours_location, class_name: 'Locations::HoursLocation', foreign_key: :locations_hours_location_id, optional: true
    belongs_to :holding_library, class_name: 'Locations::Library', foreign_key: :holding_library_id, optional: true

    has_and_belongs_to_many :delivery_locations, -> { distinct },
                            class_name: 'Locations::DeliveryLocation',
                            join_table: 'locations_holdings_delivery',
                            foreign_key: 'locations_delivery_location_id',
                            association_foreign_key: 'locations_holding_location_id'

    validates :aeon_location, :recap_electronic_delivery_location, :open,
              :requestable, :always_requestable, :circulates, inclusion: { in: [true, false] }

    after_create :set_defaults
    after_initialize :associate_non_staff_only_delivery_locations, if: :new_record?

    private

    def set_defaults
      self.aeon_location = false if aeon_location.blank?
      self.recap_electronic_delivery_location = false if recap_electronic_delivery_location.blank?
      self.open = true if self.open.blank?
      self.requestable = true if requestable.blank?
      self.always_requestable = false if always_requestable.blank?
      self.circulates = true if circulates.blank?
    end

    def associate_non_staff_only_delivery_locations
      DeliveryLocation.all.reject(&:staff_only?).each do |public_dl|
        delivery_locations << public_dl
      end
    end
  end
end

app/models/locations/hours_location.rb
# frozen_string_literal: true

module Locations
  class HoursLocation < ActiveRecord::Base
    include Locations::Labeled
    include Locations::Coded
  end
end

app/models/locations/library.rb
# frozen_string_literal: true

module Locations
  class Library < ActiveRecord::Base
    include Locations::Labeled
    include Locations::Coded
  end
end

app/controllers/locations/application_controller.rb
# frozen_string_literal: true

module Locations
  class ApplicationController < ActionController::Base
  end
end

app/controllers/locations/delivery_locations_controller.rb
# frozen_string_literal: true

require_dependency 'locations/application_controller'

module Locations
  class DeliveryLocationsController < ApplicationController
    before_action :set_delivery_location, only: %i[show edit update destroy]

    # GET /delivery_locations
    def index
      @delivery_locations = DeliveryLocation.all
    end

    # GET /digital_locations
    def digital_locations
      @delivery_locations = DeliveryLocation.select(&:digital_location?)
      render :index
    end

    # GET /delivery_locations/1
    def show; end

    # GET /delivery_locations/new
    def new
      @delivery_location = DeliveryLocation.new
    end

    # GET /delivery_locations/1/edit
    def edit; end

    # POST /delivery_locations
    def create
      @delivery_location = DeliveryLocation.new(delivery_location_params)

      if @delivery_location.save
        redirect_to @delivery_location, notice: 'Delivery location was successfully created.'
      else
        flash.now[:error] = @delivery_location.errors.full_messages
        render :new
      end
    end

    # PATCH/PUT /delivery_locations/1
    def update
      if @delivery_location.update(delivery_location_params)
        redirect_to @delivery_location, notice: 'Delivery location was successfully updated.'
      else
        flash.now[:error] = @delivery_location.errors.full_messages
        render :edit
      end
    end

    # DELETE /delivery_locations/1
    def destroy
      @delivery_location.destroy
      redirect_to delivery_locations_url, notice: 'Delivery location was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_delivery_location
      @delivery_location = DeliveryLocation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def delivery_location_params
      params.require(:delivery_location).permit(:label, :address, :phone_number, :contact_email, :gfa_pickup, :staff_only, :pickup_location, :digital_location, :locations_library_id, :locations_holding_location_id)
    end
  end
end

app/controllers/locations/floors_controller.rb
require_dependency "locations/application_controller"

module Locations
  class FloorsController < ApplicationController
    before_action :set_floor, only: [:show, :edit, :update, :destroy]

    # GET /floors
    def index
      @floors = Floor.all
    end

    # GET /floors/1
    def show
    end

    # GET /floors/new
    def new
      @floor = Floor.new
    end

    # GET /floors/1/edit
    def edit
    end

    # POST /floors
    def create
      @floor = Floor.new(floor_params)

      if @floor.save
        redirect_to library_floor_path(@floor, @floor.locations_library_id), notice: 'Floor was successfully created.'
      else
        flash.now[:error] = @floor.errors.full_messages
        render :new
      end
    end

    # PATCH/PUT /floors/1
    def update
      if @floor.update(floor_params)
        redirect_to library_floor_path(@floor, @floor.locations_library_id), notice: 'Floor was successfully updated.'
      else
        flash.now[:error] = @floor.errors.full_messages
        render :edit
      end
    end

    # DELETE /floors/1
    def destroy
      library_id = @floor.locations_library_id
      @floor.destroy
      redirect_to library_floors_path(library_id), notice: 'Floor was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_floor
        @floor = Floor.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def floor_params
        params.require(:floor).permit(:label, :floor_plan_image, :starting_point, :walkable_areas, :locations_library_id)
      end
  end
end

app/controllers/locations/holding_locations_controller.rb
# frozen_string_literal: true

require_dependency 'locations/application_controller'

module Locations
  class HoldingLocationsController < ApplicationController
    before_action :set_holding_location, only: %i[show edit update destroy]

    # GET /holding_locations
    def index
      @holding_locations = HoldingLocation.order(:code)
    end

    # GET /holding_locations/1
    def show; end

    # GET /holding_locations/new
    def new
      @holding_location = HoldingLocation.new
    end

    # GET /holding_locations/1/edit
    def edit; end

    # POST /holding_locations
    def create
      @holding_location = HoldingLocation.new(holding_location_params)

      if @holding_location.save
        redirect_to @holding_location, notice: 'Holding location was successfully created.'
      else
        flash.now[:error] = @holding_location.errors.full_messages
        render :new
      end
    end

    # PATCH/PUT /holding_locations/1
    def update
      if @holding_location.update(holding_location_params)
        redirect_to @holding_location, notice: 'Holding location was successfully updated.'
      else
        flash.now[:error] = @holding_location.errors.full_messages
        render :edit
      end
    end

    # DELETE /holding_locations/1
    def destroy
      @holding_location.destroy
      redirect_to holding_locations_url, notice: 'Holding location was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_holding_location
      @holding_location = HoldingLocation.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def holding_location_params
      params.require(:holding_location).permit(:label, :code,
                                               :aeon_location, :recap_electronic_delivery_location, :open,
                                               :requestable, :always_requestable, :circulates, :locations_library_id,
                                               :holding_library_id, :locations_hours_location_id,
                                               delivery_location_ids: [])
    end
  end
end

app/controllers/locations/home_controller.rb
# frozen_string_literal: true

require_dependency 'locations/application_controller'

module Locations
  class HomeController < ApplicationController
    # GET /locations
    def index; end
  end
end

app/controllers/locations/hours_locations_controller.rb
# frozen_string_literal: true

require_dependency 'locations/application_controller'

module Locations
  class HoursLocationsController < ApplicationController
    before_action :set_hours_location, only: %i[show edit update destroy]

    # GET /hours_locations
    def index
      @hours_locations = HoursLocation.all
    end

    # GET /hours_locations/1
    def show; end

    # GET /hours_locations/new
    def new
      @hours_location = HoursLocation.new
    end

    # GET /hours_locations/1/edit
    def edit; end

    # POST /hours_locations
    def create
      @hours_location = HoursLocation.new(hours_location_params)

      if @hours_location.save
        redirect_to @hours_location, notice: 'Hours location was successfully created.'
      else
        flash.now[:error] = @hours_location.errors.full_messages
        render :new
      end
    end

    # PATCH/PUT /hours_locations/1
    def update
      if @hours_location.update(hours_location_params)
        redirect_to @hours_location, notice: 'Hours location was successfully updated.'
      else
        flash.now[:error] = @hours_location.errors.full_messages
        render :edit
      end
    end

    # DELETE /hours_locations/1
    def destroy
      @hours_location.destroy
      redirect_to hours_locations_url, notice: 'Hours location was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_hours_location
      @hours_location = HoursLocation.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def hours_location_params
      params.require(:hours_location).permit(:code, :label)
    end
  end
end

app/controllers/locations/libraries_controller.rb
# frozen_string_literal: true

require_dependency 'locations/application_controller'

module Locations
  class LibrariesController < ApplicationController
    before_action :set_library, only: %i[show edit update destroy]

    # GET /libraries
    def index
      @libraries = Library.all.order(:order, :label)
    end

    # GET /libraries/1
    def show; end

    # GET /libraries/new
    def new
      @library = Library.new
    end

    # GET /libraries/1/edit
    def edit; end

    # POST /libraries
    def create
      @library = Library.new(library_params)

      if @library.save
        redirect_to @library, notice: 'Library was successfully created.'
      else
        flash.now[:error] = @library.errors.full_messages
        render :new
      end
    end

    # PATCH/PUT /libraries/1
    def update
      respond_to do |format|
        format.html do
          if @library.update(library_params)
            redirect_to @library, notice: 'Library was successfully updated.'
          else
            flash.now[:error] = @library.errors.full_messages
            render :edit
          end
        end
        format.js do
          @library.update(order: params[:order])
        end
      end
    end

    # DELETE /libraries/1
    def destroy
      @library.destroy
      redirect_to libraries_url, notice: 'Library was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def library_params
      params.require(:library).permit(:label, :code, :order)
    end
  end
end

app/helpers/locations/application_helper.rb
# frozen_string_literal: true

module Locations
  module ApplicationHelper
    def bootstrap_class_for(flash_type)
      case flash_type
      when 'success'
        'alert-success'   # Green
      when 'error'
        'alert-danger'    # Red
      when 'alert'
        'alert-warning'   # Yellow
      when 'notice'
        'alert-info'      # Blue
      else
        flash_type.to_s
      end
    end
  end
end

app/helpers/locations/delivery_locations_helper.rb
# frozen_string_literal: true

module Locations
  module DeliveryLocationsHelper
  end
end

app/helpers/locations/floors_helper.rb
module Locations
  module FloorsHelper
  end
end

app/helpers/locations/holding_locations_helper.rb
# frozen_string_literal: true

module Locations
  module HoldingLocationsHelper
    def boolean_properties_labels
      {
        aeon_location: 'This is an Aeon request location',
        recap_electronic_delivery_location: 'Items in the location are eligible for electronic delivery from ReCAP',
        open: 'This is an open location',
        requestable: 'Items in this location are requestable',
        always_requestable: 'Items in this location are always requestable, even when checked out',
        circulates: 'Items in this location circulate'
      }
    end

    def hours_render(hl)
      hl.hours_location.nil? ? '' : link_to(hl.hours_location.code, hl.hours_location)
    end

    def holding_library_render(hl)
      hl.holding_library.nil? ? '' : link_to(hl.holding_library.code, hl.holding_library)
    end
  end
end

app/helpers/locations/hours_locations_helper.rb
# frozen_string_literal: true

module Locations
  module HoursLocationsHelper
  end
end

app/views/locations/delivery_locations/_form.html.erb
<%= form_for(@delivery_location, html: { class: 'form-horizonal' }) do |f| %>

  <fieldset>
  <div class="form-group">
    <%= f.label 'Delivery Location', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :label, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label 'Library', class: 'col-sm-2 control-label'%>
    <div class="col-sm-10">
      <%= f.collection_select :locations_library_id, Locations::Library.all, :id, :label, {prompt: "Select a Library"}, {class: "form-control"} %>
    </div>
  </div>



  <div class="form-group">
    <%= f.label 'Street Address', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :address %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Phone Number', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :phone_number %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Contact E-mail Address', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :contact_email %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'GFA System Pickup Code', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :gfa_pickup %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <%= f.check_box(:staff_only) %> Items are for Staff-Only
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <%= f.check_box(:pickup_location) %> This is a Pickup Location
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <%= f.check_box(:digital_location) %> This is a Digital Location
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>
</fieldset>
<% end %>

app/views/locations/delivery_locations/edit.html.erb
<h1>Editing Delivery Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @delivery_location %> |
<%= link_to 'All Delivery Locations', delivery_locations_path %>

app/views/locations/delivery_locations/index.html.erb
<h1>Delivery Locations</h1>

<table class="table tablesorter tablesorter-blue sortonly">
  <thead>
    <tr>
      <th>Label</th>
      <th>Library</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Contact E-mail</th>
      <th>GFA Pickup</th>
      <th>Staff only</th>
      <th>Pickup Location</th>
      <th>Digital Location</th>
      <th colspan="1" class="sorter-false filter-false"></th>
      <th colspan="1" class="sorter-false filter-false"></th>
    </tr>
  </thead>

  <tbody>
    <% @delivery_locations.each do |delivery_location| %>
      <tr>
        <td><%= link_to delivery_location.label, delivery_location %></td>
        <td><%= link_to delivery_location.library.code, delivery_location.library %></td>
        <td><%= delivery_location.address %></td>
        <td><%= delivery_location.phone_number %></td>
        <td><%= delivery_location.contact_email %></td>
        <td><%= delivery_location.gfa_pickup %></td>
        <td><%= delivery_location.staff_only %></td>
        <td><%= delivery_location.pickup_location %></td>
        <td><%= delivery_location.digital_location %></td>
        <td><%= link_to 'Edit', edit_delivery_location_path(delivery_location) %></td>
        <td><%= link_to 'Destroy', delivery_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery location', new_delivery_location_path %> |
<%= link_to 'View as JSON', format: :json %>

app/views/locations/delivery_locations/new.html.erb
<h1>New Delivery Location</h1>

<%= render 'form' %>

<%= link_to 'All Delivery Locations', delivery_locations_path %>

app/views/locations/delivery_locations/show.html.erb
<p>
  <strong>Label:</strong>
  <%= @delivery_location.label %>
</p>

<p>
  <strong>Library:</strong>
  <%= link_to @delivery_location.library.code, @delivery_location.library %>
</p>

<p>
  <strong>Address:</strong>
  <%= @delivery_location.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @delivery_location.phone_number %>
</p>

<p>
  <strong>Contact mail:</strong>
  <%= @delivery_location.contact_email %>
</p>

<p>
  <strong>GFA Pickup:</strong>
  <%= @delivery_location.gfa_pickup %>
</p>

<p>
  <strong>Staff only:</strong>
  <%= @delivery_location.staff_only %>
</p>

<p>
  <strong>Pickup Location:</strong>
  <%= @delivery_location.pickup_location %>
</p>

<p>
  <strong>Digital Location:</strong>
  <%= @delivery_location.digital_location %>
</p>

<%= link_to 'Edit', edit_delivery_location_path(@delivery_location) %> |
<%= link_to 'View as JSON', format: :json %> |
<%= link_to 'All Delivery Locations', delivery_locations_path %>